package storage

var dummyData = map[string][]map[string][]string{
	"domain": {
		{
			"id":             {"1"},
			"nsgroupId":      {"1"},
			"name":           {"example.tld"},
			"domainId":       {"D1234567-TLD"},
			"updatedDate":    {"2009-05-29 20:13:00"},
			"creationDate":   {"2000-10-08 00:45:00"},
			"expirationDate": {"2010-10-08 00:44:59"},
			"domainStatus":   {"clientDeleteProhibited", "clientRenewProhibited", "clientTransferProhibited"},
			"ownerHandle":    {"5372808-ERL"},
			"adminHandle":    {"5372809-ERL"},
			"techHandle":     {"5372811-ERL"},
			"dnssec":         {"signedDelegation"},
		},
		{
			"id":             {"2"},
			"nsgroupId":      {"2"},
			"name":           {"google.com"},
			"updatedDate":    {"2014-05-19 04:00:17"},
			"creationDate":   {"1997-09-15 00:00:00"},
			"expirationDate": {"2020-09-13 21:00:00"},
			"domainStatus":   {"clientUpdateProhibited", "clientTransferProhibited", "clientDeleteProhibited"},
			"ownerHandle":    {"MMR-2383"},
			"adminHandle":    {"MMA-2211"},
			"techHandle":     {"MMA-2211"},
			"dnssec":         {"unsigned"},
		},
	},
	"customer": {
		{
			"handle":                 {"5372808-ERL"},
			"name.firstName":         {"EXAMPLE"},
			"name.lastName":          {"REGISTRANT"},
			"companyName":            {"EXAMPLE ORGANIZATION"},
			"address.street":         {"123 EXAMPLE STREET"},
			"address.city":           {"ANYTOWN"},
			"address.state":          {"AP"},
			"address.zipcode":        {"A1A1A1"},
			"address.country":        {"AA"},
			"phone.countryCode":      {"+1"},
			"phone.areaCode":         {"555"},
			"phone.subscriberNumber": {"5551212"},
			"fax.countryCode":        {"+1"},
			"fax.areaCode":           {"555"},
			"fax.subscriberNumber":   {"5551213"},
			"email":                  {"EMAIL@EXAMPLE.TLD"},
		},
		{
			"handle":                 {"5372809-ERL"},
			"name.firstName":         {"EXAMPLE"},
			"name.lastName":          {"REGISTRANT ADMINISTRATIVE"},
			"companyName":            {"EXAMPLE REGISTRANT ORGANIZATION"},
			"address.street":         {"123 EXAMPLE STREET"},
			"address.city":           {"ANYTOWN"},
			"address.state":          {"AP"},
			"address.zipcode":        {"A1A1A1"},
			"address.country":        {"AA"},
			"phone.countryCode":      {"+1"},
			"phone.areaCode":         {"555"},
			"phone.subscriberNumber": {"5551212"},
			"fax.countryCode":        {"+1"},
			"fax.areaCode":           {"555"},
			"fax.subscriberNumber":   {"5551213"},
			"email":                  {"EMAIL@EXAMPLE.TLD"},
		},
		{
			"handle":                 {"5372811-ERL"},
			"name.firstName":         {"EXAMPLE"},
			"name.lastName":          {"REGISTRANT TECHNICAL"},
			"companyName":            {"EXAMPLE REGISTRANT LLC"},
			"address.street":         {"123 EXAMPLE STREET"},
			"address.city":           {"ANYTOWN"},
			"address.state":          {"AP"},
			"address.zipcode":        {"A1A1A1"},
			"address.country":        {"AA"},
			"phone.countryCode":      {"+1"},
			"phone.areaCode":         {"123"},
			"phone.subscriberNumber": {"5551234"},
			"fax.countryCode":        {"+1"},
			"fax.areaCode":           {"555"},
			"fax.subscriberNumber":   {"5551213"},
			"email":                  {"EMAIL@EXAMPLE.TLD"},
		},
		{
			"handle":                 {"MMR-2383"},
			"name.firstName":         {"Dns"},
			"name.lastName":          {"Admin"},
			"companyName":            {"Google Inc."},
			"address.street":         {"1600 Amphitheatre Parkway"},
			"address.city":           {"Mountain View"},
			"address.state":          {"CA"},
			"address.zipcode":        {"94043"},
			"address.country":        {"US"},
			"phone.countryCode":      {"+1"},
			"phone.areaCode":         {"650"},
			"phone.subscriberNumber": {"2530000"},
			"fax.countryCode":        {"+1"},
			"fax.areaCode":           {"650"},
			"fax.subscriberNumber":   {"6188571"},
			"email":                  {"dns-admin@google.com"},
		},
		{
			"handle":                 {"MMA-2211"},
			"name.firstName":         {"DNS"},
			"name.lastName":          {"Admin"},
			"companyName":            {"Google Inc."},
			"address.street":         {"2400 E. Bayshore Pkwy"},
			"address.city":           {"Mountain View"},
			"address.state":          {"CA"},
			"address.zipcode":        {"94043"},
			"address.country":        {"US"},
			"phone.countryCode":      {"+1"},
			"phone.areaCode":         {"650"},
			"phone.subscriberNumber": {"3300100"},
			"fax.countryCode":        {"+1"},
			"fax.areaCode":           {"650"},
			"fax.subscriberNumber":   {"6181499"},
			"email":                  {"dns-admin@google.com"},
		},
	},
	"nameserver": {
		{
			"id":        {"1"},
			"nsgroupId": {"1"},
			"name":      {"NS01.EXAMPLE-REGISTRAR.TLD"},
		},
		{
			"id":        {"2"},
			"nsgroupId": {"1"},
			"name":      {"NS02.EXAMPLE-REGISTRAR.TLD"},
		},
		{
			"id":        {"3"},
			"nsgroupId": {"2"},
			"name":      {"ns1.google.com"},
		},
		{
			"id":        {"4"},
			"nsgroupId": {"2"},
			"name":      {"ns2.google.com"},
		},
		{
			"id":        {"5"},
			"nsgroupId": {"2"},
			"name":      {"ns3.google.com"},
		},
		{
			"id":        {"6"},
			"nsgroupId": {"2"},
			"name":      {"ns4.google.com"},
		},
	},
	"whois": {
		{
			"id":          {"1"},
			"updatedDate": {"2014-06-01 11:00:07"},
		},
	},
}
